name = "atomic"
description = "Standalone Ada/SPARK bindings to GCC atomic built-ins"
version = "0.3.0"

licenses = "MIT"
authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
website = "https://github.com/Fabien-Chouteau/atomic"
tags = ["atomic", "spark", "embedded", "nostd"]
