on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_native:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        gnat_version: [^10, ^11, ^12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v1
        with:
          toolchain: gnat_native${{ matrix.gnat_version }} gprbuild --disable-assistant
      - run: alr build
      - run: cd tests && alr build --validation
      - run: cd tests && alr run

  build_arm_elf:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        gnat_version: [^10, ^11, ^12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v1
        with:
          toolchain: gnat_arm_elf${{ matrix.gnat_version }} gprbuild --disable-assistant

      - run: cd tests/armv6m && alr build --validation
        if: ${{ matrix.gnat_version == '^12' }}
      - run: cd tests/rp2040_spinlock && alr build --validation
        if: ${{ matrix.gnat_version == '^12' }}

      - run: cd tests/armv6m && alr build --validation -- -XTESTS_RUNTIME=zfp-cortex-m0
        if: ${{ matrix.gnat_version != '^12' }}
      - run: cd tests/rp2040_spinlock && alr build --validation  -- -XTESTS_RUNTIME=zfp-cortex-m0
        if: ${{ matrix.gnat_version != '^12' }}
